var http = require("http");
var fs = require("fs")


var server = http.createServer((req, res)=>{
    res.writeHead(200, {'Content-Type': 'text/html; charset=utf-8'});
    res.end('<!DOCTYPE html><head><meta charset = "UTF-8"><title>Главное меню - Школа 44</title><link rel = "stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"><style>html,body{ background-color: lightskyblue; height:100%;max-height:100%; width:100%; margin:0 auto; padding: 0; } .up { overflow: hidden; background-color: #333; position: relative; font-size: 110%; } .up a { float: left; color: #f2f2f2; text-align: center; padding: 0.8% 0.9%; text-decoration: none; } .up a:hover { background-color: #ddd; color: black; } .up a.active { background-color: #4CAF50; color: white; } .leftside{ height: 100%; background-color: floralwhite; opacity: 0.8; width: 20%; float: left; } .rightside{ background-color: floralwhite; opacity: 0.8; width: 20%; float: right; height: 100%; } .content{ height: 100%; background-color: rgb(173, 173, 173); width: 60%; float: left; } .contentpicture{ margin: inherit; background-color: lawngreen; height: 140px; margin: 10px 15px auto; background-size: cover; background-image: url("https://avatars.mds.yandex.net/get-altay/225456/2a0000015f1aeec796d836d5819f29bebd7e/XXXL"); } .container{ width:100%; height: 100%; } .wrapper{ margin: 0 auto; height: 93.595%; width:90%; background-color: rgb(173, 173, 173); } .contexmenu{ margin: 0 auto; padding:0; } .contexmenu p{ font-size: 110%; padding: 1% 2%; background-color: orange; text-decoration: none; margin: 0; } .contexmenu p.top{ font-size: 120%; padding: 1.2% 1.5%; background-color: seagreen; text-decoration: none; margin: 0; text-align:center; } hr{ margin: 0; color: lightgrey; }</style><script src = "main.js"> </script><meta name="viewport" content="width=device-width"></head><script></script><body id = "body" scroll="no" onload="corecting()"><div class="up"><a class="active" href="main.html">Home</a><a href="#news">Расписание</a><a href="contacts.html">Контакты</a><a href="about.html">Про нас</a><a href = "Login.html" class="active" style="float:right">Вход в ИОС</a></div><div class="wrapper"><div class="container"><div id= "leftside" class="leftside"><div class="contexmenu"><p class="top">Преподавательский состав</p><hr><p><a>Кафедра математики</a><hr><p><a>Кафедра биологии</a><hr><p><a>Кафедра физики</a><hr><p><a>Кафедра химии</a></p><hr></div></div><div id="content" class="content"><div class="contentpicture"></div></div><div id= "rightside" class="rightside">sdfsdf</div></div></div></body>');
});

server.listen(228, '127.0.0.1');
console.log("hui sosi")
